import type { Blueprint } from "@/lib/types";

/**
 * Generate a complete markdown guide from a blueprint.
 * This produces a universal, offline-ready document that can be used
 * with any AI tool (Claude, ChatGPT, Gemini, etc.).
 */
export function generateBlueprintMarkdown(blueprint: Blueprint): string {
  const lines: string[] = [];

  lines.push(`# ${blueprint.title}`);
  lines.push("");
  lines.push(`> ${blueprint.subtitle}`);
  lines.push("");
  lines.push(`**Methodology:** ${blueprint.methodology} ${blueprint.version}`);
  lines.push(`**Steps:** ${blueprint.stepCount} | **Estimated Time:** ${blueprint.estimatedTime}`);
  lines.push(`**Artifacts Produced:** ${blueprint.artifactsProduced.join(", ")}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Required Inputs
  lines.push("## Before You Start — Required Inputs");
  lines.push("");
  lines.push("Gather the following information before beginning:");
  lines.push("");
  for (const input of blueprint.requiredInputs) {
    lines.push(`### ${input.name}`);
    lines.push(`${input.description}`);
    lines.push(`*Format: ${input.format}*`);
    lines.push("");
  }
  lines.push("---");
  lines.push("");

  // Steps
  for (const step of blueprint.steps) {
    lines.push(`## Step ${step.id}: ${step.title}`);
    lines.push("");
    lines.push(`**Purpose:** ${step.purpose}`);
    lines.push(`**Estimated Time:** ${step.estimatedTime}`);
    lines.push("");

    // Prompt
    lines.push("### Prompt");
    lines.push("");
    lines.push("Copy and paste the following prompt into your AI tool:");
    lines.push("");
    lines.push("```");
    lines.push(step.prompt);
    lines.push("```");
    lines.push("");

    // Expected Output
    lines.push("### Expected Output");
    lines.push("");
    lines.push(step.expectedOutput);
    lines.push("");

    // Artifacts
    if (step.artifacts.length > 0) {
      lines.push("### Artifacts");
      lines.push("");
      for (const artifact of step.artifacts) {
        lines.push(`- **${artifact.name}** (${artifact.format}): ${artifact.description}`);
        if (artifact.columns && artifact.columns.length > 0) {
          lines.push(`  - Columns: ${artifact.columns.join(" | ")}`);
        }
      }
      lines.push("");
    }

    // Checkpoint
    lines.push(`### Checkpoint: ${step.checkpoint.title}`);
    lines.push("");
    for (const item of step.checkpoint.items) {
      lines.push(`- [ ] ${item.label}`);
      if (item.description) {
        lines.push(`  *${item.description}*`);
      }
    }
    lines.push("");
    lines.push(`**If checkpoint fails:** ${step.checkpoint.failAction}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Footer
  lines.push("## Completion");
  lines.push("");
  lines.push(`Congratulations! You have completed the ${blueprint.title} blueprint.`);
  lines.push("");
  lines.push("### Artifacts Produced:");
  lines.push("");
  for (const artifact of blueprint.artifactsProduced) {
    lines.push(`- [x] ${artifact}`);
  }
  lines.push("");
  lines.push("---");
  lines.push(`*Generated by ElitePMPrompts.com — ${blueprint.methodology} ${blueprint.version} Blueprint*`);

  return lines.join("\n");
}

/**
 * Generate Claude Projects setup instructions for a blueprint.
 */
export function generateClaudeProjectSetup(blueprint: Blueprint): string {
  const lines: string[] = [];

  lines.push(`# Claude Projects Setup — ${blueprint.title}`);
  lines.push("");
  lines.push("## How to Use This Blueprint with Claude Projects");
  lines.push("");
  lines.push("Claude Projects allows you to create a persistent workspace with custom instructions");
  lines.push("and knowledge files. This guide walks you through setting up a project optimized");
  lines.push(`for the ${blueprint.title} workflow.`);
  lines.push("");
  lines.push("### Step 1: Create a New Project");
  lines.push("");
  lines.push("1. Go to [claude.ai](https://claude.ai)");
  lines.push("2. Click **Projects** in the left sidebar");
  lines.push(`3. Click **New Project** and name it "${blueprint.title}"`);
  lines.push("");
  lines.push("### Step 2: Set Custom Instructions");
  lines.push("");
  lines.push("Paste the following into the **Custom Instructions** field:");
  lines.push("");
  lines.push("```");
  lines.push(`You are a ${blueprint.methodology} ${blueprint.version} methodology expert assisting with ${blueprint.title}.`);
  lines.push("");
  lines.push(`Your role is to produce complete, methodology-compliant PM artifacts following the ${blueprint.methodology} framework.`);
  lines.push("");
  lines.push("Key principles:");
  lines.push(`- Follow ${blueprint.methodology} ${blueprint.version} terminology and practices exactly`);
  lines.push("- Produce structured, tabular artifacts (not narrative text)");
  lines.push("- Include all required fields for each artifact type");
  lines.push("- Flag any missing inputs rather than making assumptions");
  lines.push("- Reference specific methodology phases and ceremonies");
  lines.push("```");
  lines.push("");
  lines.push("### Step 3: Upload Knowledge Files");
  lines.push("");
  lines.push("Upload the following to the project knowledge base:");
  lines.push("");
  lines.push(`1. **This blueprint guide** (the markdown file: \`${blueprint.slug}-blueprint.md\`)`);
  lines.push("2. **Your organizational data** — any context documents about your:");
  for (const input of blueprint.requiredInputs) {
    lines.push(`   - ${input.name}`);
  }
  lines.push("");
  lines.push("### Step 4: Run the Blueprint");
  lines.push("");
  lines.push("Start a new conversation in the project and copy each step's prompt");
  lines.push("from the blueprint guide. The project context will automatically be available.");
  lines.push("");
  lines.push("### Tips");
  lines.push("");
  lines.push("- Keep each step in the same conversation for context continuity");
  lines.push("- If you need to restart a step, reference the previous artifacts");
  lines.push("- Use the checkpoints at the end of each step to verify output quality");
  lines.push("- Export final artifacts to your project management tool");
  lines.push("");
  lines.push("---");
  lines.push(`*Generated by ElitePMPrompts.com — ${blueprint.methodology} ${blueprint.version} Blueprint*`);

  return lines.join("\n");
}

/**
 * Trigger a download of a text file in the browser.
 */
export function downloadTextFile(content: string, filename: string): void {
  if (typeof window === "undefined") return;

  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download a complete blueprint pack (markdown guide + Claude setup).
 */
export function downloadBlueprintPack(blueprint: Blueprint): void {
  const markdown = generateBlueprintMarkdown(blueprint);
  downloadTextFile(markdown, `${blueprint.slug}-blueprint.md`);

  // Small delay before second download
  setTimeout(() => {
    const setup = generateClaudeProjectSetup(blueprint);
    downloadTextFile(setup, `${blueprint.slug}-claude-setup.md`);
  }, 500);
}
